[package]
name = "waffle0823/luau-typed-promise"
description = "A Promise library for Roblox with types"
version = "0.1.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"
